### ISSUE TITLE
問題回覆..須改善

### ISSUE THREAD

**Issue by osstw** [forjason/hr_sf#2]
一、每日出勤狀況報 須要加入 廠區按鈕 
二、每日匯入 須去除 考勤機編號問題
三、統計表 都須改善wizard 程序 過濾條件的選擇
四、上班工時統計，這裡要對 早上忘打卡、下午打了二次，或早上打了二次下午忘記打卡的判斷做 設置規則

**Comment by forjason** [comment]
1. 每日出勤狀況報 須要加入 廠區按鈕 
完成

2. 每日匯入 須去除 考勤機編號問題
完成。考勤记录上的location字段，现在直接改为Char。
